### ISSUE TITLE
hipblasIdamax mismatch between CHIP-SPV and HIPAMD

### ISSUE THREAD

**Issue by pvelesko** [CHIP-SPV/hipBLAS#8]
Refer to the comment in the following kernel:
```
    case CEED_NORM_MAX: {
      CeedInt indx;
      if (CEED_SCALAR_TYPE == CEED_SCALAR_FP32) {
        CeedCallHipblas(ceed, hipblasIsamax(handle, length, (float *)d_array, 1, &indx));
      } else {
        CeedCallHipblas(ceed, hipblasIdamax(handle, length, (double *)d_array, 1, &indx));
      }
      CeedScalar normNoAbs;
      CeedCallHip(ceed, hipMemcpy(&normNoAbs, impl->d_array + indx /* -1 when using HIPAMD */, sizeof(CeedScalar), hipMemcpyDeviceToHost));
      *norm = fabs(normNoAbs);
      break;
    }
```

The input array is something like 
```
0, -1, 2, -3, 4, -5, 6, -7, 8, -9
```

Seems that the CHIP-SPV hipBLAS is returning the index of regular `max()` instead of `absmax()`

**Comment by Sarbojit2019** [comment]
@pvelesko, can you please mention the expected output and the output you see with CHIP-SPV hipBLAS? Also can you point me to the absmax() or is it blasmax() you meant :)?

**Comment by pvelesko** [comment]
For the example input, HIPAMD returns index 9 (-9) and CHIP-SPV returns index 8 (8) this would be explained by be hipamd evaluating `max(abs(x))` and CHIP-SPV evaluating `max(x)`

**Comment by Sarbojit2019** [comment]
Commit : https://github.com/CHIP-SPV/hipBLAS/commit/0f140ed6ce9d2ee20273b588818f161281f90aa6 has the fix. Please let me know if you still see the issue.
